//
// Created by xgallom on 4/10/20.
//

#ifndef XLINEAR_ROOT_XLINEAR_CONFIG_FLOATING_H
#define XLINEAR_ROOT_XLINEAR_CONFIG_FLOATING_H

#cmakedefine01 XLINEAR_CFG_FLOATING_USE_ULP_COMPARE
#cmakedefine XLINEAR_CFG_FLOATING_ULP_MAX_COMPARE_DISTANCE @XLINEAR_CFG_FLOATING_ULP_MAX_COMPARE_DISTANCE@

#endif //XLINEAR_ROOT_XLINEAR_CONFIG_XLINEAR_FLOATING_H
