//
// Created by xgallom on 4/10/20.
//

#ifndef XLINEAR_ROOT_XLINEAR_INCLUDE_XLINEAR_FLOATING_H
#define XLINEAR_ROOT_XLINEAR_INCLUDE_XLINEAR_FLOATING_H

#include "floating/Floating.h"

#endif //XLINEAR_ROOT_XLINEAR_INCLUDE_XLINEAR_FLOATING_H
